<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="referenceObjects\Graphoscope\FGraphs.fs" />
    <Compile Include="referenceObjects\Graphoscope\DiGraphs.fs" />
    <Compile Include="referenceObjects\QuikGraph\AdjGraphs.fs" />
    <Compile Include="HelperFunctions.fs" />
    <Compile Include="GraphoscopeBenchmark.fs" />
    <Compile Include="QuikGraphBenchmark.fs" />
    <Compile Include="BenchmarkSettings.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" Version="0.15.2" />
    <PackageReference Include="QuikGraph" Version="2.5.0" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\..\src\Graphoscope\Graphoscope.fsproj" />
  </ItemGroup>

</Project>
